/**
 * Philippine address data with province -> cities -> barangays (representative samples)
 * and shipping zone mapping.
 */

export const SHIPPING_ZONES = {
  'Metro Manila': { label: 'Metro Manila', rate: 220 },
  'Luzon': { label: 'Luzon', rate: 250 },
  'Visayas': { label: 'Visayas', rate: 200 },
  'Mindanao': { label: 'Mindanao', rate: 250 },
};

// Province -> zone mapping
export const PROVINCE_ZONE = {
  // Metro Manila
  'Metro Manila': 'Metro Manila',
  'NCR': 'Metro Manila',
  // Luzon
  'Abra': 'Luzon', 'Agusan del Norte': 'Mindanao', 'Agusan del Sur': 'Mindanao',
  'Aklan': 'Visayas', 'Albay': 'Luzon', 'Antique': 'Visayas',
  'Apayao': 'Luzon', 'Aurora': 'Luzon', 'Basilan': 'Mindanao',
  'Bataan': 'Luzon', 'Batanes': 'Luzon', 'Batangas': 'Luzon',
  'Benguet': 'Luzon', 'Biliran': 'Visayas', 'Bohol': 'Visayas',
  'Bukidnon': 'Mindanao', 'Bulacan': 'Luzon', 'Cagayan': 'Luzon',
  'Camarines Norte': 'Luzon', 'Camarines Sur': 'Luzon', 'Camiguin': 'Mindanao',
  'Capiz': 'Visayas', 'Catanduanes': 'Luzon', 'Cavite': 'Luzon',
  'Cebu': 'Visayas', 'Compostela Valley': 'Mindanao', 'Cotabato': 'Mindanao',
  'Davao del Norte': 'Mindanao', 'Davao del Sur': 'Mindanao', 'Davao Oriental': 'Mindanao',
  'Davao Occidental': 'Mindanao', 'Dinagat Islands': 'Mindanao',
  'Eastern Samar': 'Visayas', 'Guimaras': 'Visayas', 'Ifugao': 'Luzon',
  'Ilocos Norte': 'Luzon', 'Ilocos Sur': 'Luzon', 'Iloilo': 'Visayas',
  'Isabela': 'Luzon', 'Kalinga': 'Luzon', 'La Union': 'Luzon',
  'Laguna': 'Luzon', 'Lanao del Norte': 'Mindanao', 'Lanao del Sur': 'Mindanao',
  'Leyte': 'Visayas', 'Maguindanao': 'Mindanao', 'Marinduque': 'Luzon',
  'Masbate': 'Luzon', 'Misamis Occidental': 'Mindanao', 'Misamis Oriental': 'Mindanao',
  'Mountain Province': 'Luzon', 'Negros Occidental': 'Visayas', 'Negros Oriental': 'Visayas',
  'Northern Samar': 'Visayas', 'Nueva Ecija': 'Luzon', 'Nueva Vizcaya': 'Luzon',
  'Occidental Mindoro': 'Luzon', 'Oriental Mindoro': 'Luzon', 'Palawan': 'Luzon',
  'Pampanga': 'Luzon', 'Pangasinan': 'Luzon', 'Quezon': 'Luzon',
  'Quirino': 'Luzon', 'Rizal': 'Luzon', 'Romblon': 'Luzon',
  'Samar': 'Visayas', 'Sarangani': 'Mindanao', 'Siquijor': 'Visayas',
  'Sorsogon': 'Luzon', 'South Cotabato': 'Mindanao', 'Southern Leyte': 'Visayas',
  'Sultan Kudarat': 'Mindanao', 'Sulu': 'Mindanao', 'Surigao del Norte': 'Mindanao',
  'Surigao del Sur': 'Mindanao', 'Tarlac': 'Luzon', 'Tawi-Tawi': 'Mindanao',
  'Zambales': 'Luzon', 'Zamboanga del Norte': 'Mindanao', 'Zamboanga del Sur': 'Mindanao',
  'Zamboanga Sibugay': 'Mindanao',
};

export const PHILIPPINES_PROVINCES = [
  'Metro Manila',
  'Abra', 'Agusan del Norte', 'Agusan del Sur', 'Aklan', 'Albay', 'Antique',
  'Apayao', 'Aurora', 'Basilan', 'Bataan', 'Batanes', 'Batangas',
  'Benguet', 'Biliran', 'Bohol', 'Bukidnon', 'Bulacan', 'Cagayan',
  'Camarines Norte', 'Camarines Sur', 'Camiguin', 'Capiz', 'Catanduanes',
  'Cavite', 'Cebu', 'Compostela Valley', 'Cotabato', 'Davao del Norte',
  'Davao del Sur', 'Davao Oriental', 'Davao Occidental', 'Dinagat Islands',
  'Eastern Samar', 'Guimaras', 'Ifugao', 'Ilocos Norte', 'Ilocos Sur',
  'Iloilo', 'Isabela', 'Kalinga', 'La Union', 'Laguna', 'Lanao del Norte',
  'Lanao del Sur', 'Leyte', 'Maguindanao', 'Marinduque', 'Masbate',
  'Misamis Occidental', 'Misamis Oriental', 'Mountain Province',
  'Negros Occidental', 'Negros Oriental', 'Northern Samar', 'Nueva Ecija',
  'Nueva Vizcaya', 'Occidental Mindoro', 'Oriental Mindoro', 'Palawan',
  'Pampanga', 'Pangasinan', 'Quezon', 'Quirino', 'Rizal', 'Romblon',
  'Samar', 'Sarangani', 'Siquijor', 'Sorsogon', 'South Cotabato',
  'Southern Leyte', 'Sultan Kudarat', 'Sulu', 'Surigao del Norte',
  'Surigao del Sur', 'Tarlac', 'Tawi-Tawi', 'Zambales',
  'Zamboanga del Norte', 'Zamboanga del Sur', 'Zamboanga Sibugay',
];

export const CITIES_BY_PROVINCE = {
  'Metro Manila': [
    'Caloocan', 'Las Piñas', 'Makati', 'Malabon', 'Mandaluyong', 'Manila',
    'Marikina', 'Muntinlupa', 'Navotas', 'Parañaque', 'Pasay', 'Pasig',
    'Pateros', 'Quezon City', 'San Juan', 'Taguig', 'Valenzuela',
  ],
  'Cebu': [
    'Cebu City', 'Lapu-Lapu City', 'Mandaue City', 'Talisay City', 'Toledo City',
    'Bogo City', 'Carcar City', 'Danao City', 'Naga City', 'San Fernando',
    'Alcantara', 'Alcoy', 'Alegria', 'Aloguinsan', 'Argao', 'Asturias',
    'Badian', 'Balamban', 'Bantayan', 'Barili', 'Borbon', 'Carmen',
    'Catmon', 'Compostela', 'Consolacion', 'Cordova', 'Daanbantayan',
    'Dalaguete', 'Dumanjug', 'Ginatilan', 'Liloan', 'Madridejos',
    'Malabuyoc', 'Medellin', 'Minglanilla', 'Moalboal', 'Oslob',
    'Pilar', 'Pinamungahan', 'Poro', 'Ronda', 'Samboan', 'San Francisco',
    'San Remigio', 'Santa Fe', 'Santander', 'Sibonga', 'Sogod', 'Tabogon',
    'Tabuelan', 'Tuburan', 'Tudela',
  ],
  'Cavite': [
    'Bacoor', 'Cavite City', 'Dasmariñas', 'General Trias', 'Imus',
    'Tagaytay', 'Trece Martires', 'Alfonso', 'Amadeo', 'Gen. Emilio Aguinaldo',
    'Gen. Mariano Alvarez', 'Indang', 'Kawit', 'Magallanes', 'Maragondon',
    'Mendez', 'Naic', 'Noveleta', 'Rosario', 'Silang', 'Tanza',
  ],
  'Laguna': [
    'Calamba', 'San Pedro', 'Sta. Rosa', 'Biñan', 'Cabuyao',
    'Los Baños', 'San Pablo City', 'Alaminos', 'Bay', 'Calauan',
    'Cavinti', 'Famy', 'Kalayaan', 'Liliw', 'Luisiana', 'Lumban',
    'Mabitac', 'Magdalena', 'Majayjay', 'Nagcarlan', 'Paete', 'Pagsanjan',
    'Pakil', 'Pangil', 'Pila', 'Rizal', 'San Juan', 'Siniloan', 'Victoria',
  ],
  'Batangas': [
    'Batangas City', 'Lipa City', 'Tanauan City', 'Agoncillo', 'Alitagtag',
    'Balayan', 'Balete', 'Bauan', 'Calaca', 'Calatagan', 'Cuenca',
    'Ibaan', 'Laurel', 'Lemery', 'Lian', 'Lobo', 'Mabini', 'Malvar',
    'Mataas na Kahoy', 'Nasugbu', 'Padre Garcia', 'Rosario', 'San Jose',
    'San Juan', 'San Luis', 'San Nicolas', 'San Pascual', 'Santa Teresita',
    'Santo Tomas', 'Taal', 'Talisay', 'Taysan', 'Tingloy', 'Tuy',
  ],
  'Rizal': [
    'Antipolo City', 'Angono', 'Baras', 'Binangonan', 'Cainta',
    'Cardona', 'Jalajala', 'Morong', 'Pililla', 'Rodriguez',
    'San Mateo', 'Tanay', 'Taytay', 'Teresa',
  ],
  'Bulacan': [
    'Malolos', 'Meycauayan', 'San Jose del Monte', 'Angat', 'Balagtas',
    'Baliuag', 'Bocaue', 'Bulakan', 'Bustos', 'Calumpit', 'Doña Remedios Trinidad',
    'Guiguinto', 'Hagonoy', 'Marilao', 'Norzagaray', 'Obando', 'Pandi',
    'Paombong', 'Plaridel', 'Pulilan', 'San Ildefonso', 'San Miguel',
    'San Rafael', 'Santa Maria',
  ],
  'Pampanga': [
    'Angeles City', 'San Fernando City', 'Apalit', 'Arayat', 'Bacolor',
    'Candaba', 'Floridablanca', 'Guagua', 'Lubao', 'Mabalacat',
    'Macabebe', 'Magalang', 'Masantol', 'Mexico', 'Minalin',
    'Porac', 'San Luis', 'San Simon', 'Santa Ana', 'Santa Rita',
    'Santo Tomas', 'Sasmuan',
  ],
  'Quezon': [
    'Lucena City', 'Tayabas City', 'Agdangan', 'Alabat', 'Atimonan',
    'Buenavista', 'Burdeos', 'Calauag', 'Candelaria', 'Catanauan',
    'Dolores', 'General Luna', 'General Nakar', 'Guinayangan', 'Gumaca',
    'Infanta', 'Jomalig', 'Lopez', 'Lucban', 'Macalelon', 'Mauban',
    'Mulanay', 'Padre Burgos', 'Pagbilao', 'Panukulan', 'Patnanungan',
    'Perez', 'Pitogo', 'Plaridel', 'Polillo', 'Quezon', 'Real',
    'Sampaloc', 'San Andres', 'San Antonio', 'San Francisco', 'San Narciso',
    'Sariaya', 'Tagkawayan', 'Tiaong', 'Unisan',
  ],
  'Iloilo': [
    'Iloilo City', 'Passi City', 'Ajuy', 'Alimodian', 'Anilao', 'Badiangan',
    'Balasan', 'Banate', 'Barotac Nuevo', 'Barotac Viejo', 'Batad',
    'Bingawan', 'Cabatuan', 'Calinog', 'Carles', 'Concepcion', 'Dingle',
    'Dueñas', 'Dumangas', 'Estancia', 'Guimbal', 'Igbaras', 'Janiuay',
    'Lambunao', 'Leganes', 'Lemery', 'Leon', 'Maasin', 'Miagao',
    'Mina', 'New Lucena', 'Oton', 'Pavia', 'Pototan', 'San Dionisio',
    'San Enrique', 'San Joaquin', 'San Miguel', 'San Rafael', 'Santa Barbara',
    'Sara', 'Tigbauan', 'Tubungan', 'Zarraga',
  ],
  'Davao del Sur': [
    'Davao City', 'Digos City', 'Bansalan', 'Davao City', 'Hagonoy',
    'Jose Abad Santos', 'Kiblawan', 'Magsaysay', 'Malalag', 'Matanao',
    'Padada', 'Santa Cruz', 'Sulop',
  ],
  'Negros Occidental': [
    'Bacolod City', 'Bago City', 'Cadiz City', 'Escalante City', 'Himamaylan City',
    'Kabankalan City', 'La Carlota City', 'Sagay City', 'San Carlos City',
    'Silay City', 'Sipalay City', 'Talisay City', 'Victorias City',
    'Binalbagan', 'Calatrava', 'Candoni', 'Cauayan', 'Enrique B. Magalona',
    'Hinigaran', 'Hinoba-an', 'Ilog', 'Isabela', 'La Castellana',
    'Manapla', 'Moises Padilla', 'Murcia', 'Pontevedra', 'Pulupandan',
    'Salvador Benedicto', 'San Enrique', 'Toboso', 'Valladolid',
  ],
};

// For provinces not in CITIES_BY_PROVINCE, generate a generic list
export function getCitiesForProvince(province) {
  return CITIES_BY_PROVINCE[province] || [`${province} City`, `${province} Municipality`];
}

// Barangays - provide common ones for major cities
export const BARANGAYS_BY_CITY = {
  'Cebu City': [
    'Adlaon', 'Agsungot', 'Apas', 'Babag', 'Bacayan', 'Banilad', 'Basak Pardo',
    'Basak San Nicolas', 'Binaliw', 'Bonbon', 'Budla-an', 'Buhisan', 'Bulacao',
    'Buot-Taup Pardo', 'Busay', 'Calamba', 'Cambinocot', 'Capitol Site', 'Carreta',
    'Central', 'Cogon Pardo', 'Cogon Ramos', 'Day-as', 'Ermita', 'Guadalupe',
    'Guba', 'Hippodromo', 'Inayawan', 'Kalubihan', 'Kalunasan', 'Kamagayan',
    'Kasambagan', 'Kinasang-an Pardo', 'Labangon', 'Lahug', 'Lorega', 'Luz',
    'Mabini', 'Mabolo', 'Malago', 'Manipis', 'Manueva', 'Marcelo', 'Mipangi',
    'Monument Pardo', 'Pahina Central', 'Pahina San Nicolas', 'Pamutan',
    'Pardo', 'Pari-an', 'Paril', 'Pasil', 'Pit-os', 'Poblacion Pardo',
    'Pulangbato', 'Pung-ol-Sibugay', 'Punta Princesa', 'Quiot Pardo',
    'Sambag 1', 'Sambag 2', 'San Antonio', 'San Jose', 'San Nicolas Central',
    'San Roque', 'Santa Cruz', 'Sapangdaku', 'Sirao', 'Sudlon 1', 'Sudlon 2',
    'T. Padilla', 'Tabunan', 'Tagba-o', 'Taptap', 'Tejero', 'Tinago', 'Tisa',
    'To-ong Pardo', 'Toong', 'Zapatera',
  ],
  'Lapu-Lapu City': [
    'Agus', 'Babag', 'Bankal', 'Baring', 'Basak', 'Buaya', 'Calawisan',
    'Canjulao', 'Caubian', 'Caw-oy', 'Cokoy', 'Cordova', 'Gabi', 'Gun-ob',
    'Ibo', 'Looc', 'Mactan', 'Maribago', 'Marigondon', 'Market', 'Nueve de Febrero',
    'Olango', 'Pajac', 'Pajo', 'Patagan', 'Poblacion', 'Punta Engaño',
    'Pusok', 'Sabang', 'Santa Rosa', 'Subabasbas', 'Talima', 'Tingo', 'Tungasan',
  ],
  'Quezon City': [
    'Alicia', 'Bagbag', 'Bagong Pag-asa', 'Bagong Silangan', 'Bagumbayan',
    'Bagumbuhay', 'Bahay Toro', 'Balingasa', 'Balumbato', 'Batasan Hills',
    'Bayanihan', 'Blue Ridge A', 'Blue Ridge B', 'Botocan', 'Bungad',
    'Camp Aguinaldo', 'Capri', 'Central', 'Claro', 'Commonwealth', 'Culiat',
    'Damar', 'Damayang Lagi', 'Del Monte', 'Dioquino Zobel', 'Don Manuel',
    'Doña Aurora', 'Doña Faustina 1', 'Doña Faustina 2', 'Doña Imelda',
    'Doña Josefa', 'Duyan-Duyan', 'E. Rodriguez', 'East Kamias', 'Escopa 1',
    'Fairview', 'Gulod', 'Holy Spirit', 'Horseshoe', 'Immaculate Concepcion',
    'Kaligayahan', 'Kalusugan', 'Kamuning', 'Katipunan', 'Kaunlaran',
    'Kristong Hari', 'Krus na Ligas', 'Laging Handa', 'Libis',
    'Lourdes', 'Loyola Heights', 'Maharlika', 'Malaya', 'Manresa',
    'Mariana', 'Mariblo', 'Masambong', 'Matandang Balara', 'Milagrosa',
    'Nagkaisang Nayon', 'Nayong Kanluran', 'New Era', 'North Fairview',
    'Novaliches Proper', 'Obrero', 'Old Capitol Site', 'Paang Bundok',
    'Pag-ibig sa Nayon', 'Paligsahan', 'Paltok', 'Pansol', 'Paraiso',
    'Phil-Am', 'Pinagkaisahan', 'Pinyahan', 'Pinagbuhatan', 'Project 2',
    'Project 3', 'Project 4', 'Project 6', 'Project 7', 'Project 8',
    'Quirino 2-A', 'Quirino 3-A', 'Ramon Magsaysay', 'Roxas', 'Sacred Heart',
    'Salvacion', 'San Agustin', 'San Bartolome', 'San Isidro', 'San Jose',
    'San Martin de Porres', 'San Roque', 'Santo Cristo', 'Santo Niño',
    'Santol', 'Sauyo', 'Signal Village', 'Sikatuna Village', 'Silangan',
    'Socorro', 'South Triangle', 'Talayan', 'Tandang Sora', 'Tatalon',
    'Teacher\'s Village East', 'Ugong Norte', 'Unang Sigaw', 'UP Campus',
    'Vargas', 'Veterans Village', 'Villa Maria Clara', 'Violago-Imelda',
    'West Kamias', 'White Plains', 'Wilshire',
  ],
  'Manila': [
    'Binondo', 'Ermita', 'Intramuros', 'Malate', 'Paco', 'Pandacan',
    'Port Area', 'Quiapo', 'Sampaloc', 'San Andres', 'San Miguel',
    'San Nicolas', 'Santa Ana', 'Santa Cruz', 'Santa Mesa', 'Tondo',
  ],
  'Makati': [
    'Bangkal', 'Bel-Air', 'Carmona', 'Cembo', 'Comembo', 'Dasmariñas',
    'East Rembo', 'Forbes Park', 'Guadalupe Nuevo', 'Guadalupe Viejo',
    'Kasilawan', 'La Paz', 'Magallanes', 'Olympia', 'Palanan', 'Pembo',
    'Pinagkaisahan', 'Pio del Pilar', 'Poblacion', 'Post Proper Northside',
    'Post Proper Southside', 'Rizal', 'San Antonio', 'San Isidro',
    'San Lorenzo', 'Santa Cruz', 'Singkamas', 'South Cembo', 'Tejeros',
    'Urdaneta', 'West Rembo',
  ],
  'Pasig': [
    'Bagong Ilog', 'Bagong Katipunan', 'Bambang', 'Buting', 'Caniogan',
    'Dela Paz', 'Kalawaan', 'Kapasigan', 'Kapitolyo', 'Malinao',
    'Manggahan', 'Maybunga', 'Oranbo', 'Palatiw', 'Pinagbuhatan',
    'Pineda', 'Rosario', 'Sagad', 'San Antonio', 'San Joaquin',
    'San Jose', 'San Miguel', 'San Nicolas', 'Santa Cruz', 'Santa Lucia',
    'Santa Rosa', 'Santo Tomas', 'Santolan', 'Sumilang', 'Ugong',
  ],
  'Taguig': [
    'Bagumbayan', 'Bambang', 'Calzada', 'Central Bicutan', 'Central Signal Village',
    'Fort Bonifacio', 'Hagonoy', 'Ibayo-Tipas', 'Katuparan', 'Ligid-Tipas',
    'Lower Bicutan', 'Maharlika Village', 'Napindan', 'New Lower Bicutan',
    'North Daang Hari', 'North Signal Village', 'Palingon', 'Pinagsama',
    'San Miguel', 'Santa Ana', 'South Daang Hari', 'South Signal Village',
    'Tanyag', 'Tuktukan', 'Upper Bicutan', 'Ususan', 'Wawa', 'Western Bicutan',
  ],
  'Davao City': [
    'Acacia', 'Agdao', 'Alambre', 'Alejandra Navarro', 'Alfonso Angliongto',
    'Angalan', 'Atan-awe', 'Baganihan', 'Bago Aplaya', 'Bago Gallera',
    'Bago Oshiro', 'Baguio', 'Balengaeng', 'Baliok', 'Bangkas Heights',
    'Bantol', 'Baracatan', 'Barangay 1-40', 'Buhangin', 'Bunawan',
    'Cadalian', 'Carmen', 'Catalunan Grande', 'Catalunan Pequeño',
    'Celing', 'Centro', 'Colo', 'Communal', 'Crossing Bayabas',
    'Dacudao', 'Dalag', 'Dalagdag', 'Daliao', 'Daliaon Plantation',
    'Datu Salumay', 'Dominga', 'Dumoy', 'Eden', 'Fatima', 'Gatungan',
    'Gov. Paciano Bangoy', 'Gov. Vicente Duterte', 'Gumalang', 'Ilang',
    'Inayangan', 'Indangan', 'Kap. Tomas Monteverde', 'Lacson',
    'Lamanan', 'Lampianao', 'Langub', 'Lapu-Lapu', 'Lara', 'Leon Garcia',
    'Lizada', 'Los Amigos', 'Lubogan', 'Lumiad', 'Ma-a', 'Mabuhay',
    'Magsaysay', 'Magtuod', 'Mahayag', 'Malabog', 'Malagos', 'Malalag',
    'Manuel Guianga', 'Mapula', 'Marapangi', 'Mario Guianga', 'Matina Aplaya',
    'Matina Crossing', 'Matina Pangi', 'Matina URC', 'Megkawayan', 'Mintal',
    'Mudiang', 'Mulig', 'New Carmen', 'New Valencia', 'Pampanga',
    'Panacan', 'Panaligao', 'Pangyan', 'Paquibato', 'Paradise Embak',
    'Piapi', 'Poblacion', 'Puan', 'Riverside', 'Salapawan', 'Salaysay',
    'Samal', 'San Antonio', 'Santo Niño', 'Sasa', 'Sibulan', 'Sirawan',
    'Sirib', 'Suawan', 'Subasta', 'Talomo Proper', 'Tamugan', 'Tapak',
    'Tawan-tawan', 'Tibuloy', 'Tibungco', 'Tigatto', 'Toril', 'Tugbok',
    'Tungkalan', 'Ubalde', 'Ula', 'Vicente Hizon', 'Waan', 'Wangan',
    'Wines', 'Wilfredo Aquino',
  ],
  'Bacolod City': [
    'Alijis', 'Banago', 'Bata', 'Cabug', 'Estefania', 'Felisa',
    'Granada', 'Handumanan', 'Mandalagan', 'Mansilingan', 'Montevista',
    'Pahanocoy', 'Punta Taytay', 'Singcang-Airport', 'Sum-ag', 'Taculing',
    'Tangub', 'Villamonte', 'Vista Alegre',
    'Barangay 1', 'Barangay 2', 'Barangay 3', 'Barangay 4', 'Barangay 5',
    'Barangay 6', 'Barangay 7', 'Barangay 8', 'Barangay 9', 'Barangay 10',
    'Barangay 11', 'Barangay 12', 'Barangay 13', 'Barangay 14', 'Barangay 15',
    'Barangay 16', 'Barangay 17', 'Barangay 18', 'Barangay 19', 'Barangay 20',
    'Barangay 21', 'Barangay 22', 'Barangay 23', 'Barangay 24', 'Barangay 25',
    'Barangay 26', 'Barangay 27', 'Barangay 28', 'Barangay 29', 'Barangay 30',
    'Barangay 31', 'Barangay 32', 'Barangay 33', 'Barangay 34', 'Barangay 35',
    'Barangay 36', 'Barangay 37', 'Barangay 38', 'Barangay 39', 'Barangay 40',
  ],
};

export function getBarangaysForCity(city) {
  return BARANGAYS_BY_CITY[city] || ['Poblacion', 'Barangay 1', 'Barangay 2', 'Barangay 3', 'Barangay 4', 'Barangay 5', 'Other'];
}

export function getShippingZone(province) {
  return PROVINCE_ZONE[province] || 'Luzon';
}

export function getShippingRate(province) {
  const zone = getShippingZone(province);
  return SHIPPING_ZONES[zone]?.rate || 180;
}

export const WORLD_COUNTRIES = [
  'Philippines', 'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
  'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
  'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize',
  'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
  'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
  'Canada', 'Cape Verde', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
  'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
  'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
  'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
  'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea',
  'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
  'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
  'Jordan', 'Kazakhstan', 'Kenya', 'Kuwait', 'Kyrgyzstan', 'Laos',
  'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
  'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
  'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco',
  'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
  'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
  'North Korea', 'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama',
  'Papua New Guinea', 'Paraguay', 'Peru', 'Poland', 'Portugal', 'Qatar',
  'Romania', 'Russia', 'Rwanda', 'Saudi Arabia', 'Senegal', 'Serbia',
  'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Somalia', 'South Africa',
  'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
  'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
  'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia',
  'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates',
  'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Venezuela',
  'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe',
];